---
title: "Partial migration"
description: |
  Do White Sturgeon exhibit partial migration?
author:
  - name: Seb Dalgarno
    url: https://github.com/sebdalgarno
date: 04-14-2021
output:
  distill::distill_article:
    self_contained: false
draft: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# What is partial migration?
Partial migration describes the phenomenon of different migratory behaviours within a population. Three types of seasonal partial migration are defined in Chapman (2011a): 1. non-breeding partial migration occurs when migrants and residents breed sympatricaly but overwinter apart; 2. breeding partial migration occurs when migrants and residents overwinter together but breed allopatrically; 3. skiiped breeding partial migration occurs when individuals do not migrate to breed every year. A fourth kind of partial pigration over shorter spatiotempporal scales is also defined. Partial diel vertical migration (DVM) occurs when some individuals migrate verticale but others remain in the same pace within the water column.

Each migratory group is called a 'contingent'. In some cases, contingents differ phenotypically (e.g. resident rainbow trout and migrant steelhead trout) making their identification relateively easy. Technologies to directly (e.g. capture-recapture, telemetry) or indirectly (e.g., otolith microchemistry, stable isotope, molecular analysis) observe movement patterns can be used.

In Chapman's (2011a) review of partial migration, they state that Acipensiformes exhibit skipped breeding partial migration as adults only spawn every few years. No other evidence of partial migration is provided. However, breeding partial migration in Acipensiformes is disputed in Rideout (2005), who state that cases where process of vitellogenesis takes longer than a year (multiyear ripening) are not capable of spawning every year and therefore should be distinguished from other iteroparous fish exhibiting partial migration. 

# Why does partial migration occur?
All hypothesized causes for partial migration are based on the premise that migratory behaviour is an adaptive response to availability of resources or presence of predators, which fluctuate over space and time (seasonally and daily); each individual migrates or remains resident to maximize evolutionary fitness. 

In general, fish with lower body condition are more likely to be pushed into suboptimal conditions, i.e., less likely to take refuge migration and more likely to take feeding migration. 
In the case fo skipped breeding partial migration, spawning migration can be deferred in years when an individuals doesn’t have enough energy for grand and egg production. 


have caused me to more deeply think about how impoundment has impacted the WS transboundary reach subpopulation

Main questions are:
1. has impoundment blocked partial migration strategy that would have existed beforehand? (i.e., were WS migrating to spawning sites outside of transboundary reach)

evidence for this:
genetic population Columbia-Snake suggesting that these regions mixed historically
divergent migration strategies in lake sturgeon in barrier-free HEC - divergent strategy in shortnose?

potential evidence against:
nechako and middle fraser distinct populations - suggesting hig spawning site fidelity, despite lack of barriers

2. What are the consequences and management implications for this potential disruption in partial migration?
transboundary reach should not be managed as a separate population
recruitment may have been helped by very productive spawning grounds elsewhere
disruption in salmonid partial migration likely large consequences on nutrient input and tropchic effects

There are major management implications for failing to recognize partial migration in populations. 

When the ability of populations to carry out partial migration is hindered or eliminated due to impoundment, this can have large consequences on ecosystem and implications for management.

sturgeon and 
Partial migration in sturgeon species has not been well studied (at least relative to salmonids). A recent paper by Kessel et al. (2018) showed that 5 divergent migration strategies exist in Lake Sturgeon within the barrier-free Huron-Erie Corridor (HEC) of the Great Lakes. 




